controllers:
    resource: ../src/Controller/
    type: attribute
app_book_list:
    path: /books
    controller: App\Controller\BookController::list
    methods: GET
    defaults:
        _api_resource_class: App\Entity\Book
        _api_collection_operation_name: get
api_login_check:
    path: /api/login_check
